name: Verify Assertion Failure

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test-native:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Build
          run: |
              cd test
              ./build_and_run

        - name: Verify assertion fails
          run: |
            cd test
            if ./build/Example; then
              echo "ERROR: Test should have failed but passed"
              exit 1
            else
              echo "Test failed as expected"
              exit 0
            fi

  test-emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: mymindstorm/setup-emsdk@v14

      - name: Build
        run: |
          cd test
          ./em_build_and_test

      - name: Verify assertion fails
        run: |
          cd test
          if node web-build/Example.js; then
            echo "ERROR: Test should have failed"
            exit 1
          else
            echo "Test failed as expected"
            exit 0
          fi
